### ISSUE TITLE
Pre-Highlight using Search

### ISSUE THREAD

**Issue by Avinash-Cognizer** [agentcooper/react-pdf-highlighter#176] opened 2022-03-04 08:52 UTC
Hello,
**How can we highlight word/section using search** ? Right now the only way to Highlight any text is when you know its coordinates.
what If I am given some word or sentences, let's say via an api, and I want to highlight it when the PDF renders
is there any work-around for this ?

**Comment by Avinash-Cognizer** [comment] 2022-03-08 06:08
Hey @agentcooper can you shed some light ?

**Comment by holub008** [comment] 2022-04-07 22:20
My team has been hacking on this from the parent component, using `window.PDFViewer`; beyond being kind of gross in using a global intended for debug, I believe it's the cause of infrequent crashes when our users search (I'm sure swapping out the viewer is not healthy).

```js
  search = (searchValue) => {
    if (window.PdfViewer?.viewer) {
      if (!this.getFindController()) {
        // We re-create the PDFViewer bc the PDFFindController needs to be initialized here
        window.PdfViewer.viewer = new PDFViewer({
          container: window.PdfViewer.containerNode,
          eventBus: window.PdfViewer.eventBus,
          enhanceTextSelection: true,
          removePageBorders: true,
          linkService: window.PdfViewer.linkService,
          findController: new PDFFindController({ eventBus: window.PdfViewer.eventBus, linkService: window.PdfViewer.linkService }),
        });
        window.PdfViewer.eventBus.on('updatetextlayermatches', this.calculateMatchProgress);
        window.PdfViewer.init();
      }
      const findController = this.getFindController();
      findController.executeCommand('find', {
        query: searchValue,
        highlightAll: true,
        phraseSearch: true,
      });
      this.setState({ searchValue });
    }
  }
```

I would **love** to move this internal to `PDFHighlighter`, using a `search` prop (default to `undefined` = no search to run).

**Comment by qaisershehzad** [comment] 2022-04-19 08:02
Hi @holub008 , I tried adding this PDFFindController but no success.. text is not highlighted .. if you can share sample App.tsx or component how you are using this would be huge favor.

Also I am looking to have page navigation (previous/next button to navigation between pages) as well if any idea please share how I can achieve  in react-pdf-highlighter.

**Comment by Daan-Grashoff** [comment] 2022-07-10 19:20
> My team has been hacking on this from the parent component, using `window.PDFViewer`; beyond being kind of gross in using a global intended for debug, I believe it's the cause of infrequent crashes when our users search (I'm sure swapping out the viewer is not healthy).
> 
> ```js
>   getFindController = () => window?.PdfViewer?.viewer?.findController;
> 
>   search = (searchValue) => {
>     if (window.PdfViewer?.viewer) {
>       if (!this.getFindController()) {
>         // We re-create the PDFViewer bc the PDFFindController needs to be initialized here
>         window.PdfViewer.viewer = new PDFViewer({
>           container: window.PdfViewer.containerNode,
>           eventBus: window.PdfViewer.eventBus,
>           enhanceTextSelection: true,
>           removePageBorders: true,
>           linkService: window.PdfViewer.linkService,
>           findController: new PDFFindController({ eventBus: window.PdfViewer.eventBus, linkService: window.PdfViewer.linkService }),
>         });
>         window.PdfViewer.eventBus.on('updatetextlayermatches', this.calculateMatchProgress);
>         window.PdfViewer.init();
>       }
>       const findController = this.getFindController();
>       findController.executeCommand('find', {
>         query: searchValue,
>         highlightAll: true,
>         phraseSearch: true,
>       });
>       this.setState({ searchValue });
>     }
>   }
> ```
> 
> I would **love** to move this internal to `PDFHighlighter`, using a `search` prop (default to `undefined` = no search to run).

Hi could you show a more complete code snippet? I'm having issues when I try to run the executeCommand on the findcontroller

Thanks!

**Comment by holub008** [comment] 2022-07-10 20:19
Our team opened a PR here: https://github.com/agentcooper/react-pdf-highlighter/pull/185. We package the fork, which includes some other QOL goodies, on NPM: https://www.npmjs.com/package/@darian-lp/react-pdf-highlighter

It's our goal to move off the fork once the PRs are merged in, but we couldn't wait for search/zoom/rotate (standard functions on any PDF viewer) to be implemented.

**Comment by Daan-Grashoff** [comment] 2022-07-10 21:30
Awesome! Thanks, I'm gonna check it out!

**Comment by LibertyNLP** [comment] 2022-07-18 10:53
Hi , I wish my work can help you.
I have figured out a solution of pdf.js annotation, use only pdf.js dist, and it is very easy to import into your project.

Demo and source code: https://demos.libertynlp.com/#/pdfjs-annotation
Demo video:https://www.youtube.com/watch?v=IYD7WKzx-yc&t=3s

functions:
① highlight : highlight selected text;
② underline : underline selected text;
③ edit: edit annotation ( copy/delete/add comment/navigate );
④ output annotations : output annotations for importing;
⑤ import annotations : import annotations for current file;
⑥ download annotations : download annotations and comments text;
⑦ undo annotations : undo annotations in current page;
⑧ help : open help file;

**Comment by RutgerSwirski** [comment] 2022-08-22 13:58
I just wanted to say a MASSIVE thanks to @holub008 and his team for getting this implemented in a way more dev friendly way!!!

**Closed** 2024-09-14 17:05 UTC
